# Generated by Django 4.0.4 on 2022-04-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('userpass', models.CharField(max_length=100)),
                ('user_joinDate', models.DateField()),
            ],
        ),
    ]
