# Generated by Django 4.0.4 on 2022-04-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('raw_words', models.IntegerField()),
                ('processed', models.CharField(max_length=255)),
                ('len_process', models.IntegerField()),
                ('replaced', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('minutes', models.IntegerField()),
                ('contributor_id', models.IntegerField()),
                ('submitted', models.DateField()),
                ('tags', models.CharField(max_length=255)),
                ('nutrition', models.CharField(max_length=255)),
                ('n_steps', models.IntegerField()),
                ('steps', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('ingredients', models.CharField(max_length=500)),
                ('n_ingredients', models.IntegerField()),
            ],
        ),
    ]
