# Generated by Django 4.0.4 on 2022-04-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutrition',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.JSONField(),
        ),
    ]
