# Generated by Django 4.0.4 on 2022-04-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_name_ingredient_raw_ingr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutrition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.TextField(),
        ),
    ]
