# Generated by Django 4.0.4 on 2022-04-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_ingredients_alter_recipe_nutrition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
