# Generated by Django 4.0.4 on 2022-04-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_contributor_id_alter_recipe_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='submitted',
            field=models.CharField(default='', max_length=255),
        ),
    ]
